name: Clean up

on:
  workflow_run:
    workflows: ["create a one-time only REPOB repository_dispatch event that triggers REPOA"]
    types:
      - completed

jobs:
  clean_up_response_file:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Wait for 120 seconds (2 mins)
        run: sleep 120

      - name: Get repository files (equivalent to git pull)
        uses: actions/checkout@v2

      - name: Remove file
        run: rm response
        
      - name: Commit and push changes
        run: git config --global user.email "j622amilah@gmail.com"; git config --global user.name "CodeSolutions2"; git config --global pull.rebase true; git add .; git commit -m "add files"; git push https://${{ secrets.REPOB_FRONTEND }}@github.com/CodeSolutions2/frontend_backend_message_passing_central_repository_v0.git
