name: create a one-time only REPOB repository_dispatch event that triggers REPOA

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - run: rm response
      - run: input_text="$(cat cb.txt | cut -d '|' -f 1)"
      - run: echo "$input_text" > response
      - run: REPOA_NAME="$(cat cb.txt | cut -d '|' -f 2)"
      - run: echo "$REPOA_NAME" >> response
      
      - name: Dispatch event with payload
        uses: CodeSolutions2/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOB_FRONTEND }}
          event_type: trigger-event
          client_payload: '{"fromRepoB": "$input_text"}'
          
      - run: date >> response
      - run: curl -H "Accept:application/vnd.github+json" -X GET https://api.github.com/repos/CodeSolutions2/run_GitHub_Actions/dispatches >> response

      - name: Commit and push changes
        run: git config --global user.email "j622amilah@gmail.com"; git config --global user.name "CodeSolutions2"; git config --global pull.rebase true; git add .; git commit -m "add files"; git push https://${{ secrets.REPOB_FRONTEND }}@github.com/CodeSolutions2/run_GitHub_Actions.git
