name: Dispatch event

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get files from run_GitHub_Actions
      - uses: actions/checkout@v2
