name: bash commands and then save results to repository in a file called response

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: echo "$(cat cb.txt | cut -d '|' -f 2)\n" > response
      - run: echo "$github.event.repository.name\n" > response
      - run: echo "$github.actor\n" > response
      - run: echo "$GITHUB_ACTOR\n" > response
      - run: echo "$github.repository_owner" > response

      - name: Commit and push changes
        run: git config --global user.email "j622amilah@gmail.com"; git config --global user.name "CodeSolutions2"; git add .; git commit -m "add files"; git push https://${{ secrets.REPOB_BACKEND }}@github.com/CodeSolutions2/run_GitHub_Actions.git
