name: create a one-time only REPOB repository_dispatch event that triggers REPOA

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Get repository files (equivalent to git pull)
        uses: actions/checkout@v2

      - name: Run commands
        run: rm response; input_text="$(cat cb.txt | cut -d '|' -f 1)"; echo "Input text is $input_text" > response; REPOA_NAME="$(cat cb.txt | cut -d '|' -f 2)"; echo "Repository name is $REPOA_NAME" >> response; curl -L -X POST -H "Accept:application/vnd.github+json" -H "Authorization:token ${{ secrets.REPOA_MY_CHATBOT }}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/CodeSolutions2/my_chatbot/dispatches -d '{"event_type":"trigger-event","client_payload":{"fromrepob":"$input_text"}}' >> response; date >> response; curl -H "Accept:application/vnd.github+json" -X GET https://api.github.com/repos/CodeSolutions2/my_chatbot/dispatches >> response

      - name: Commit and push changes back to repository
        run:  git config --global user.email "j622amilah@gmail.com"; git config --global user.name "CodeSolutions2"; git config --global pull.rebase true; git add .; git commit -m "add files"; git push https://${{ secrets.REPOB_FRONTEND }}@github.com/CodeSolutions2/run_GitHub_Actions.git
