name: automatically reset REPOB key with any change to repo

on:
  push:
    branches:
      - main
    
jobs:
  reset_key:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get repository files (equivalent to git pull)
        uses: actions/checkout@v2
        
      - name: Reset the key automatically
        uses: actions/github-script@v4
        env:
          REPOB_FRONTEND: '${{ secrets.REPOB_FRONTEND }}'
        with:
          github-token: ${{ secrets.REPOB_FRONTEND }}
          script: |
            var n = 1;
            var alpha = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'; 
            var num = '0123456789'; 
            let alpha_arr = alpha.split(''); 
            let num_arr = num.split('');
            let val_that_is_0_or_1 = Math.round(Math.random());
            var new_salt_length = val_that_is_0_or_1*(n-1) + 1;
            console.log('new_salt_length: ', new_salt_length);

            // make a vector filled with 0 or 1 that is letnum_selection long
            var letnum_selection = [];
            for (let i=0; i<new_salt_length; i++) { letnum_selection.push(Math.round(Math.random())); }
            console.log('letnum_selection: ', letnum_selection);
            
            var salt = letnum_selection.map((row) => { 
              if (row == 0) { 
                let val = Math.round(Math.random()*alpha_arr.length);
                console.log('val: ', val);
                return alpha_arr[val]; 
              } else { 
                let val = Math.round(Math.random()*num_arr.length);
                console.log('val: ', val);
                return num_arr[val]; 
              } 
            });
            console.log('salt: ', salt);
            
            salt = salt.join('');
            console.log('salt: ', salt);

            const { REPOB_FRONTEND } = process.env
            let new_auth = `${REPOB_FRONTEND}`;
            console.log('new_auth: ', new_auth);
            if (Math.round(Math.random()) == 0) {
              // salt front
              new_auth = salt+new_auth;
            } else {
              // salt back
              new_auth = new_auth+salt;
            }
            
            new_auth = btoa(new_auth); // This will be displayed in the file
            const fs = require('fs');
            fs.writeFileSync('.github/.env', new_auth);

      - name: Commit and push changes back to repository
        run:  git config --global user.email "j622amilah@gmail.com"; git config --global user.name "CodeSolutions2"; git checkout main; git pull; git merge main --ff-only; git add .; git commit -m "add files"; git push https://${{ secrets.REPOB_FRONTEND }}@github.com/CodeSolutions2/frontend_backend_message_passing_central_repository_v0.git
