name: Verify that setting secret works

on:
  push:
    branches:
      - main

jobs:
  job0_update_secret_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set new value for secret
        uses: actions/secrets@v1
        with:
          secret: MY_TEST_SECRET
          value: "new value"

    
  job0_read_secret_test:
    needs: job0_update_secret_test
    runs-on: ubuntu-latest
    
    steps:
      - name: Test if a new GitHub key was created
        run: echo "Verify that new value was set = ${{ secrets.MY_TEST_SECRET }}"
