name: Updating a GitHub key - REPOB_V0_TOKEN0

on:
  push:
    branches:
      - main
      
jobs:
  update_token:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Assign a new value to the secret
        env:
          GH_TOKEN: ${{ secrets.REPOB_V0_TOKEN0 || secrets.REPOB_V0_TOKEN1 || github.token }}
        run: |
          repoOwner=$(echo "${{ github.repository }}" | cut -d '/' -f 1);
          repoOwnerEmail="j622amilah@gmail.com";
          
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git config --global push.autoSetupRemote true;
          git pull origin main;
          git checkout main;
          git branch --set-upstream-to origin/main;
          git merge main --ff-only;
          
