name: Verify that setting secret works

on:
  push:
    branches:
      - main

jobs:
  job0_update_secret_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get repository files - probably do not need it
        uses: actions/checkout@v2
        
      - name: Assign a new value to the secret
        uses: actions/github-script@v6
        env:
          MY_TEST_SECRET: '${{ secrets.MY_TEST_SECRET }}'
        with:
          github-token: ${{ secrets.REPOB_V0_test }}
          script: |
            // Get id information about repository secret
            const { data: {key: publicKey, key_id: keyId} } = await github.rest.actions.getRepoPublicKey({...context.repo});
            
            // Normally one would encrypt the token, but assign a text value to test
            const encryptedToken = "new value";

            // Re-assign the new_secret_value to the repository secret
            await github.rest.actions.createOrUpdateRepoSecret({
                ...context.repo, 
                secret_name: 'MY_TEST_SECRET',
                encrypted_value: encryptedToken,
                key_id: keyId,
              });

  job1_read_secret_test:
    needs: job0_update_secret_test
    runs-on: ubuntu-latest
    
    steps:
      - name: Test if a new_secret_value was created
        run: echo "Verify that new value was set = ${{ secrets.MY_TEST_SECRET }}"
