name: Verify that setting secret works

on:
  push:
    branches:
      - main

jobs:
  job0_update_secret_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get repository files - probably do not need it
        uses: actions/checkout@v2
        
      - name: Assign a new value to the secret
        uses: actions/github-script@v6
        env:
          MY_TEST_SECRET: '${{ secrets.MY_TEST_SECRET }}'
        with:
          result-encoding: string
          github-token: ${{ secrets.REPOB_V0_test }}
          script: |
            const { MY_TEST_SECRET } = process.env;
            const secret_name = `${MY_TEST_SECRET}`;
            
            console.log('MY_TEST_SECRET = ', MY_TEST_SECRET)

            if (MY_TEST_SECRET == 'something') {
              console.log('same value that I manually entered')
            }

            
