name: Updating a GitHub key - REPOB_V0_TOKEN1

on:
  push:
    branches:
      - main
      
jobs:
  job0_update_REPOB_V0_TOKEN1:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Assign GH_TOKEN as environmental variable
        run: |
          echo "GitHub Secret is ${{ secrets.REPOB_V0_TOKEN1 }}";
          echo "github.token is ${{ github.token }}";
          if [[ ${{ secrets.REPOB_V0_TOKEN1 }} -eq ${{ github.token }} ]]; then;
            echo "the two are equal"
          fi
