name: Updating a GitHub key - REPOB_V0_TOKEN1

on:
  push:
    branches:
      - main
      
jobs:
  job0_update_REPOB_V0_TOKEN1:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Assign a new value to the secret
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          repoOwner="CodeSolutions2";
          repoOwnerEmail="j622amilah@gmail.com";
          repoName="frontend_backend_message_passing_central_repository_v0";
          main_directory=$(echo "/home/runner/work/$repoName");
          echo "main_directory = $main_directory";
          cd $main_directory;
          
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git config --global --add safe.directory $main_directory;
          git config --global init.defaultBranch main;
          git init;
          git pull origin main;
          git branch -m main;
          git branch --set-upstream-to origin/main;
          git checkout main;
          
          gh secret set REPOB_V0_TOKEN1 --app actions --repos $repoName
