name: Updating a GitHub key - REPOB_V0_TOKEN1

on:
  push:
    branches:
      - main
      
jobs:
  job0_update_REPOB_V0_TOKEN1:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Assign GH_TOKEN as environmental variable
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: Assign a new value to the secret
        run: gh secret set REPOB_V0_TOKEN1
