name: version1 automatically update REPOB key with GitHub

on:
  push:
    branches:
      - main

jobs:
  job0_update_secret:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REPOB_V0_test || github.token }}
    
    permissions:
      id-token: write
      
    steps:
      - name: Create a GitHub secret using gh CLI
        run: gh secret set 'REPOB_V0_test' --body "$(date +%s)" --repo ${{ github.repository }}
        env:
          REPOB_V0_test: '${{ steps.access-token.outputs.token }}'

  job1_read_secret:
    needs: job0_update_secret
    runs-on: ubuntu-latest
    
    steps:
      - name: Test if a new GitHub key was created
        run: echo "New GitHub key = ${{ secrets.REPOB_V0_test }}"
