name: Updating a GitHub key - REPOB_V0_TOKEN1

on:
  push:
    branches:
      - main
      
jobs:
  job0_update_REPOB_V0_TOKEN1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REPOB_V0_TOKEN1 }}

    permissions:
      contents: write

    steps:
      - name: Assign a new value to the secret
        run: gh secret set 'REPOB_V0_TOKEN1' "${{ secrets.REPOB_V0_TOKEN1 }}" --body "$(date +%s)" --repo ${{ github.repository }}
        env:
          REPOB_V0_TOKEN1: '${{ steps.access-token.outputs.token }}'

  job1_read_secret:
    needs: job0_update_REPOB_V0_TOKEN1
    runs-on: ubuntu-latest
    
    steps:
      - name: Test if a new GitHub key was created
        run: |
          echo "New GitHub key environmental variable= ${{ env.REPOB_V0_TOKEN1 }}";
          echo "New GitHub key verify that GitHub Secrets is set = ${{ secrets.REPOB_V0_TOKEN1 }}"
